import style from '../style/style.scss';
import layout from '../assets/layout.svg';
import home from '../assets/home.svg';
import clock from '../assets/clock.svg';
import messages from '../assets/messages.svg';
import tasks from '../assets/tasks.svg';
import security from '../assets/security.svg';
import settings from '../assets/settings.svg';
import support from '../assets/support.svg';
import group from '../assets/group.svg';
import profile from '../assets/profile.svg';
import magnifier from '../assets/magnifier.svg';
import bell from '../assets/bell.svg';
import bunny from '../assets/bunny.svg';
const titleImg = document.querySelector('.title_img');
titleImg.src = layout;
const homeImg = document.querySelector('.home_img');
homeImg.src = home;
const profileImg = document.querySelector('.profile_img');
profileImg.src = profile;
const messagesImg = document.querySelector('.messages_img');
messagesImg.src = messages;
const historyImg = document.querySelector('.history_img');
historyImg.src = clock;
const tasksImg = document.querySelector('.tasks_img');
tasksImg.src = tasks;
const groupImg = document.querySelector('.communities_img');
groupImg.src = group;
const settingsImg = document.querySelector('.settings_img');
settingsImg.src = settings;
const supportImg = document.querySelector('.support_img');
supportImg.src = support;
const securityImg = document.querySelector('.privacy_img');
securityImg.src = security;
const magnifierImg = document.querySelector('.magnifier');
magnifierImg.src = magnifier;
const bellImg = document.querySelector('.bell');
bellImg.src = bell;
const bunnyImg = document.querySelector('.bunny');
bunnyImg.src = bunny;
const bunnyGreeting = document.querySelector('.bunny_greeting');
bunnyGreeting.src = bunny;
