import style from '../style/style.scss';
import layout from '../assets/layout.svg';
import home from '../assets/home.svg';
import clock from '../assets/clock.svg';
import messages from '../assets/messages.svg';
import tasks from '../assets/tasks.svg';
import security from '../assets/security.svg';
import settings from '../assets/settings.svg';
import support from '../assets/support.svg';
import group from '../assets/group.svg';
import profile from '../assets/profile.svg';
import magnifier from '../assets/magnifier.svg';
import bell from '../assets/bell.svg';
import bunny from '../assets/bunny.svg';
import star from '../assets/star.svg';
import fork from '../assets/fork.svg';
import eye from '../assets/eye.svg';
import cat from '../assets/cat.svg';
import elephant from '../assets/elephant.svg';
import fox from '../assets/fox.svg';
import lion from '../assets/lion.svg';
const titleImg = document.querySelector('.title_img');
titleImg.src = layout;
const homeImg = document.querySelector('.home_img');
homeImg.src = home;
const profileImg = document.querySelector('.profile_img');
profileImg.src = profile;
const messagesImg = document.querySelector('.messages_img');
messagesImg.src = messages;
const historyImg = document.querySelector('.history_img');
historyImg.src = clock;
const tasksImg = document.querySelector('.tasks_img');
tasksImg.src = tasks;
const groupImg = document.querySelector('.communities_img');
groupImg.src = group;
const settingsImg = document.querySelector('.settings_img');
settingsImg.src = settings;
const supportImg = document.querySelector('.support_img');
supportImg.src = support;
const securityImg = document.querySelector('.privacy_img');
securityImg.src = security;
const magnifierImg = document.querySelector('.magnifier');
magnifierImg.src = magnifier;
const bellImg = document.querySelector('.bell');
bellImg.src = bell;
const bunnyImg = document.querySelector('.bunny');
bunnyImg.src = lion;
const bunnyGreeting = document.querySelector('.bunny_greeting');
bunnyGreeting.src = lion;
//
const starImg = document.querySelector('.star');
starImg.src = star;
const eyeImg = document.querySelector('.eye');
eyeImg.src = eye;
const forkImg = document.querySelector('.fork');
forkImg.src = fork;
const starImg2 = document.querySelector('.star2');
starImg2.src = star;
const eyeImg2 = document.querySelector('.eye2');
eyeImg2.src = eye;
const forkImg2 = document.querySelector('.fork2');
forkImg2.src = fork;
const starImg3 = document.querySelector('.star3');
starImg3.src = star;
const eyeImg3 = document.querySelector('.eye3');
eyeImg3.src = eye;
const forkImg3 = document.querySelector('.fork3');
forkImg3.src = fork;
const starImg4 = document.querySelector('.star4');
starImg4.src = star;
const eyeImg4 = document.querySelector('.eye4');
eyeImg4.src = eye;
const forkImg4 = document.querySelector('.fork4');
forkImg4.src = fork;
const starImg5 = document.querySelector('.star5');
starImg5.src = star;
const eyeImg5 = document.querySelector('.eye5');
eyeImg5.src = eye;
const forkImg5 = document.querySelector('.fork5');
forkImg5.src = fork;
const starImg6 = document.querySelector('.star6');
starImg6.src = star;
const eyeImg6 = document.querySelector('.eye6');
eyeImg6.src = eye;
const forkImg6 = document.querySelector('.fork6');
forkImg6.src = fork;
const catImg = document.querySelector('.cat');
catImg.src = cat;
const lionImg = document.querySelector('.lion');
lionImg.src = lion;
const foxImg = document.querySelector('.fox');
foxImg.src = fox;
const elephantImg = document.querySelector('.elephant');
elephantImg.src = elephant;
